export const TAB_CLICKED = 'TAB_CLICKED';
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const UPDATE_DEPARTURE_CITY_ERROR_MSG = 'UPDATE_DEPARTURE_CITY_ERROR_MSG';
